name: Turborepo Diff Check
description: Run a diff check against a specific package and its dependencies in turborepo
on:
  workflow_call:
    inputs:
      package:
        required: true
      use-last-tag:
        default: false
    outputs:
      changed:
        description: "Says whether the package has changed according to its dependencies"
        value: ${{ jobs.check-diff.outputs.changed }}
jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changedStep.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for changes
        id: changedStep
        run: |
          set +e

          if [ "${{ inputs.use-last-tag }}" = "false" ]; then
            npx turbo-ignore ${{ inputs.package }}
          else
            LAST_TAG=$(git describe --tags --abbrev=0)
            npx turbo-ignore ${{ inputs.package }} --fallback=tags/$LAST_TAG
          fi
          exit_code=$?

          set -e

          if [ $exit_code -eq "1" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

          cat $GITHUB_OUTPUT
